services:
  - type: web
    name: global-solutions
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn global_solutions.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false